sbx_sga:
  mash_ref: /mnt/isilon/marc_genomics/shared_data/RefSeq88n.msh
  checkm_ref: /mnt/isilon/marc_genomics/shared_data/CheckM2_database/uniref100.KO.1.dmnd
  bakta_ref: /mnt/isilon/marc_genomics/shared_data/bakta_db_6/db/
  genomad_ref: /mnt/isilon/marc_genomics/shared_data/genomad_db/
  sylph_ref: /mnt/isilon/marc_genomics/shared_data/sylph_db/gtdb-r220-c200-dbv1.syldb #default database
  snippy_ref: /mnt/isilon/marc_genomics/shared_data/snippy.fa