sbx_sga:
  mash_ref: /mnt/isilon/marc_genomics/shared_data/RefSeq88n.msh
  checkm_ref: /mnt/isilon/marc_genomics/shared_data/CheckM2_database/uniref100.KO.1.dmnd
  bakta_ref: /mnt/isilon/marc_genomics/shared_data/bakta_db_5/db/
  genomad_ref: /mnt/isilon/marc_genomics/shared_data/genomad_db/