name: Tests

on:
    pull_request:
      branches: [ main, master ]
    push:
      branches: [ main, master ]

jobs:
    run-tests:
        uses: ./.github/workflows/tests.yml
        secrets: inherit